CRYPT_ENGINE_COUNT:
- 1
- 1
- 1
CRYPT_ENGINE_CYCLE_PER_BLOCK: 8
CRYPT_ENGINE_SHARED: false
CRYPT_ENGINE_TYPE: effective_lpddr4_ascon
CRYPT_ENGINE_NAME: 128a_2cycle
DRAM_READ_BANDWIDTH: 8
DRAM_WRITE_BANDWIDTH: 4
EFFECTIVE_CONSERVATIVE: true
TEMPLATE_DESIGN: scone
WORDBITS: 16
