CRYPT_ENGINE_COUNT:
- 1
- 1
- 1
CRYPT_ENGINE_CYCLE_PER_BLOCK: 11
CRYPT_ENGINE_SHARED: false
CRYPT_ENGINE_TYPE: effective_lpddr4_aesgcm
DRAM_READ_BANDWIDTH: 128
DRAM_WRITE_BANDWIDTH: 128
EFFECTIVE_CONSERVATIVE: true
PE_SPAD_DEPTH:
- 256
- 16
- 64
PE_SPAD_SHARED: false
PE_SPAD_WIDTH:
- 16
- 16
- 16
PE_X: 16
PE_Y: 16
SRAM_BANKS:
- 32
SRAM_DEPTH:
- 8192
SRAM_READ_BANDWIDTH:
- 64
SRAM_SHARED: true
SRAM_WIDTH:
- 1024
SRAM_WRITE_BANDWIDTH:
- 64
TEMPLATE_DESIGN: resnet18
WORDBITS: 16
